server:
  port: 8086
  servlet:
    encoding:
      enabled: true
      charset: utf-8

    # disable sessions
    session:
      cookie:
        name: ""
      persistent: false
      timeout: 0

  tomcat:
    accesslog:
      enabled: true

spring:
    jackson:
      default-property-inclusion: non_null

mongodb-schema:
  dataaccess:
    mongodb:
      connection-string: ${MONGODB_CONNECTION_STRING:mongodb://localhost:27017}
      database-name: ${MONGODB_DATABASE_NAME:sample_weatherdata}