name: Build and Test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '24'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Maven Test
        run: mvn --batch-mode test
